### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by zspecza** [thomasdavis/seoserver#3]
Loving the concept of the project but a little surprised that it hasn't been adopted more! Also want to thank you for the backbone.js introduction screencast I bought from you ;) This will definitely come in handy for the forum software I'm building. There's the feedback :) - though, two more things... one, I noticed the seo.apiengine.io page is down, is there a reason for that? two, your example is for Apache where a .htaccess file is used, but what about PaaS hosts like Heroku, Nodejitsu, etc? Would that be more work?

**Comment by thomasdavis** [comment]
The project needs some more loving for mainstream adoption I think.

I deprecated seo.apiengine.io as a service so now just running it as a library in the mean time.

I think the Heroku cedar stack has htaccess support now but I'm not sure about other services. 

Just realized this issue is 3 months old... my apologies
